apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: healthcare
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      enableServiceLinks: false
      containers:
        - name: admin-service
          image: anshul9589/shsm-admin-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_URI
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50"
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"      # was 512Mi
              cpu: "500m"
          startupProbe:
            tcpSocket: { port: 8080 }
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8080 }
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket: { port: 8080 }
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: healthcare
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
