output "user_name" {
  description = "IAM username"
  value       = aws_iam_user.this.name
}

output "user_arn" {
  description = "IAM user ARN"
  value       = aws_iam_user.this.arn
}

output "access_key_id" {
  description = "Access key ID"
  value       = var.create_access_key ? aws_iam_access_key.access_key[0].id : null
  sensitive   = true
}

output "secret_access_key" {
  description = "Secret access key"
  value       = var.create_access_key ? aws_iam_access_key.access_key[0].secret : null
  sensitive   = true
}

output "console_password" {
  description = "Console password (auto-generated by AWS)"
  value       = var.create_console_access ? aws_iam_user_login_profile.user_profile[0].password : null
  sensitive   = true
}