# =============================================================================
# Auto-generate a sourceable env file from live infra values, on every apply.
#   Usage:  source terraform/environment/dev/cluster.env
# Handy for CI and the helper scripts (deploy.sh, LBC install, etc.).
#
# NOTE: contains account-scoped identifiers (account id, ARNs) but NO secrets —
# don't put tokens/passwords here. The file is git-ignored (see .gitignore).
# =============================================================================
resource "local_file" "cluster_env" {
  filename        = "${path.module}/cluster.env"
  file_permission = "0644"

  content = <<-EOT
    # Generated by terraform (environment/dev) — do not edit by hand.
    # Source it:  source terraform/environment/dev/cluster.env
    export AWS_REGION=${var.aws_region}
    export AWS_ACCOUNT_ID=${module.iam_account.account_id}
    export ECR_REGISTRY=${module.ecr.registry_url}
    export EKS_CLUSTER=${module.eks.cluster_name}
    export EKS_ENDPOINT=${module.eks.cluster_endpoint}
    export VPC_ID=${module.vpc.vpc_id}
    export LBC_ROLE_ARN=${module.aws_lbc_irsa.role_arn}
    export KUBECONFIG_CMD="aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}"
  EOT
}
